name: 05b- Filters - Activity Types

on:
  pull_request:
    types: [opened, synchronize]
    branches: [main]

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Running whenever a pull request is opened or updated"
